version: "3.7"
services:

  marketplace-backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    container_name: marketplace_backend
    volumes:
      - ./:/usr/src/app/backend
      - /usr/src/app/backend/node_modules
    networks:
      - mynetwork
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  mynetwork:
    driver: bridge