version: "3.7"
services:

  marketplace-backend:
    image: sipgalahad/marketplace:1.0.0
    ports:
      - "5000:5000"
    container_name: marketplace_backend
    volumes:
      - ./:/usr/src/app/backend
      - /usr/src/app/backend/node_modules
    networks:
      - mynetwork
    extra_hosts:
      - "host.docker.internal:host-gateway"
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    ports:
      - "81:81"
      - "443:443"
    depends_on:
      - marketplace-backend
networks:
  mynetwork:
    driver: bridge